- name: install ansible
  pip:
    name: ansible
    state: present
    version: "{{ bamboo_ansible_version }}"

- name: install pywinrm
  pip:
    name: pywinrm
    state: present

- name: make vault directory
  file:
    name: ~bamboo/.ansible/vault/password
    state: directory
    owner: bamboo
    group: bamboo
    mode: 0700
    recurse: true

- name: copy vault files
  copy:
    src: ~/.ansible/vault/password/{{ bamboo_vault_file }}
    dest: ~bamboo/.ansible/vault/password/{{ bamboo_vault_file }}
    owner: bamboo
    group: bamboo
    mode: 0600
