- name: install bamboo agent extra packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ bamboo_apt_packages }}"

- name: create bamboo user
  user:
    name: bamboo
    shell: /sbin/nologin
    home: /home/bamboo
    createhome: yes
    comment: Bamboo Remote Agent user
    groups:
      - docker

- name: install packages
  apt:
    name: "{{ item }}"
  with_items: "{{ bamboo_apt_packages }}"

- name: install flake8
  pip:
    name: flake8
    state: present

- name: download bamboo agent
  get_url:
    url: https://{{ bamboo_server }}/agentServer/agentInstaller/{{ bamboo_jar }}
    dest: /home/bamboo/{{ bamboo_jar }}
    owner: bamboo
    group: bamboo
    timeout: 30

- name: create bamboo service configuration file
  template:
    src: bamboo-agent.j2
    dest: /etc/default/bamboo-agent

- name: ensure bamboo agent home directory exists
  file:
    state: directory
    path: /home/bamboo/bamboo-agent-home/bin
    owner: bamboo
    group: bamboo

- name: create bamboo capabilities file
  copy:
    src: bamboo-capabilities.properties
    dest: /home/bamboo/bamboo-agent-home/bin/bamboo-capabilities.properties
    owner: bamboo
    group: bamboo

- name: create systemd unit file
  copy:
    src: bamboo-agent.service
    dest: /etc/systemd/system/bamboo-agent.service
  notify: reload systemctl

- meta: flush_handlers


- name: enable bamboo agent to start on boot
  service:
    name: bamboo-agent
    enabled: yes
