- name: Create AMIBuilder role for Bamboo
  iam_role:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    name: AMIBuilder
    state: present
    managed_policies:
      - AmazonESReadOnlyAccess
      - IAMUserSSHKeys
    assume_role_policy_document: "{{ lookup('template', 'bamboo-trust-policy.json') }}"

- name: Assign ec2-autoscaling-with-instance-profile policy to AMIBuilder
  iam_policy:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    iam_type: role
    iam_name: "AMIBuilder"
    policy_name: "ec2-autoscaling-with-instance-profile"
    state: present
    policy_json: "{{ lookup('template', 'AMIBuilder.json') }}"

- name: Create InfraBuilder role for Bamboo
  iam_role:
    region: "{{ region }}"
    profile: "{{ aws_account_name }}"
    name: InfraBuilder
    state: present
    assume_role_policy_document: "{{ lookup('template', 'bamboo-trust-policy.json') }}"

- name: Assign create-and-destroy-environments policy to InfraBuilder
  iam_policy:
    region: "{{ region }}"
    profile: "{{ aws_account_name }}"
    iam_type: role
    iam_name: "InfraBuilder"
    policy_name: "create-and-destroy-environments"
    state: present
    policy_json: "{{ lookup('template', 'InfraBuilder.json') }}"

- name: Create a role for Bamboo
  iam:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    iam_type: role
    name: bamboo_s3_push
    trust_policy: "{{ lookup('template', 'bamboo-trust-policy.json') }}"
    state: present

- name: Assign Bamboo S3 push policy to role
  iam_policy:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    iam_type: role
    iam_name: "bamboo_s3_push"
    policy_name: "bamboo_s3_push"
    state: present
    policy_json: "{{ lookup('template', 'bamboo_s3_push.json') }}"
